### ISSUE TITLE
Expiration Date Box Offset

### ISSUE THREAD

**Issue by trigun0x2** [braintree/braintree-web-drop-in#124]
### General information

* SDK/Library version: DropIn UI 1.0.0-beta.5 with SDK v3
* Environment: Sandbox
* Browser and OS: Chrome (multiple version) on MacOS 10.12.4
### Issue description

Expiration Date Box is offset:
![offset expiration date](https://i.imgur.com/Bk3Zmj7.png)

The dropinui is compiled into a large external.js file for our app and we also have various css. Not sure what other detail is needed.

Thanks!

**Comment by crookedneighbor** [comment]
Do you have a staging site or a github repo that reproduces the issue where we can take a look? I suspect it's some CSS on your site that is interfering with it.

**Comment by trigun0x2** [comment]
@crookedneighbor might be a bit complicated but you'll need to login with youtube/twitch and go to http://staging.streamlabs.com/dashboard/#/guilds/stage-s-guild. Then apply for the guild. Once that's done, we'll accept you and you'll be able to see the form

**Comment by crookedneighbor** [comment]
I'm able to join other guilds, but not that guild. Getting a 500 error.

**Comment by crookedneighbor** [comment]
Feel free to email web-drop-in-beta@braintreepayments.com if you do not want to post additional information about your staging app here.

**Comment by crookedneighbor** [comment]
I'm going to close this now, but feel free to reach out if you need additional help.

**Comment by trigun0x2** [comment]
Thanks, got caught up on some other things but we'll be looking back into this next week.

**Comment by crookedneighbor** [comment]
@trigun0x2 Let us know when you're ready for us to take a look.

**Comment by trigun0x2** [comment]
@crookedneighbor it's gonna be awhile. I can open another issue when I get there if that's easier for you guys.

**Comment by crookedneighbor** [comment]
:+1: I'll close this for now then.

**Comment by trigun0x2** [comment]
Hey you can check it out here now: https://staging.streamlabs.com/dashboard/#/guilds

Just make sure you "Join" a paid guild then it should pop up on the form.

**Comment by crookedneighbor** [comment]
I was able to reproduce it yesterday, but I went onto your site today and I no longer see the Drop-in on the page. Have you removed it or changed something else?

**Comment by trigun0x2** [comment]
@crookedneighbor it should still be there. It depends on which guild you try to join (only paid ones have it).

**Comment by crookedneighbor** [comment]
<img width="975" alt="screen shot 2017-04-26 at 9 34 08 pm" src="https://cloud.githubusercontent.com/assets/2916945/25465472/167eefc2-2ac8-11e7-9eab-785490037424.png">

Looks like someone removed the paid guilds from the list of guilds.

**Comment by trigun0x2** [comment]
I just created one: http://staging.streamlabs.com/dashboard/#/guilds/braintree-test

**Comment by crookedneighbor** [comment]
Okay, I've tracked down why this is happening. You have some CSS that looks like:

```css
type=color],
[type=date],
[type=datetime-local],
[type=datetime],
[type=email],
[type=month],
[type=number],
[type=password],
[type=search],
[type=tel],
[type=text],
[type=time],
[type=url],
[type=week],
textarea {
    display: block;
    box-sizing: border-box;
    width: 100%;
    height: 2.4375rem;
    padding: .5rem;
    border: 1px solid #cacaca;
    margin: 0 0 1rem;
    font-family: inherit;
    font-size: 1rem;
    color: #0a0a0a;
    background-color: #fefefe;
    box-shadow: inset 0 1px 2px hsla(0, 0%, 4%, .1);
    border-radius: 0;
    -webkit-transition: -webkit-box-shadow .5s, border-color .25s ease-in-out;
    transition: box-shadow .5s, border-color .25s ease-in-out;
    -webkit-appearance: none;
    -moz-appearance: none
}
```

The bit that is messing with Drop-in is:

```css
[type=number] {
    margin: 0 0 1rem;
}
```

Obviously, you're intending to target `input[type=number]`, but you're also targeting `iframe[type=number]`.

We're looking into making the Drop-in to be more resilient to this kind of thing, but a quick fix for you would be to specify that you're targeting inputs specifically.
